### PR TITLE
Text content changes

### LINKED ISSUE #77: Canvas Gradebook Formtter user response text
This issue mainly deals with adding a suitable response text for Following scenarios.

1. When user launches the Canvas Gradebook converter 
2. User loads a csv file with no schema applied validation error
3. User loads a csv file when current and final grade don't match validation error occur
4. User successfully passes all the validation error and ready for download to [Faculty center](https://csprod.dsc.umich.edu/htmldoc/eng/dftie/lsaa/htm/CU_SGRD_Upload.html)
Direct link to upload the formatted gradebook
https://csprod.dsc.umich.edu/psc/csprodop/EMPLOYEE/SA/c/NUI_FRAMEWORK.PT_LANDINGPAGE.GBL?

### PR DESCRIPTION
**Pull request by chrisrrowland**
Fixes #77 
Note:  This help link will be made functional in another issue
image

### CODE REVIEW

**Comment by pushyamig** [comment]
@chrisrrowland if you add [some predefined text defined by Gituhub](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) like **Fixes** Github will automatically link to the issue to PR as below
Screen Shot 2021-06-10 at 11 11 17 AM

This is a nice Feature we can leverage

**Comment by pushyamig** [comment]
Screen Shot 2021-06-10 at 12 01 23 PM

I would say if there is only one message to show, I would remove the number from that.

**Comment by pushyamig** [comment]
can you create an issue for remaining work ? also tag it to this epic #20 from the issue under the Epic option?
> Note: This help link will be made functional in another issue

**Comment by chrisrrowland** [comment]
> Screen Shot 2021-06-10 at 12 01 23 PM
> 
> I would say if there is only one message to show, I would remove the number from that.

Is this a reasonable solution so the formatting stays the same?
image

**Comment by chrisrrowland** [comment]
> can you create an issue for remaining work ? also tag it to this epic #20 from the issue under the Epic option?
> 
> > Note: This help link will be made functional in another issue

I read your comment as that an issue was already created.  I can create one.

**Comment by pushyamig** [comment]
> Is this a reasonable solution so the formatting stays the same?

Frankly I don't care But if that effect the way you code and how it works with other features that share common code Then I am fine leaving as it. When this goes to actual testing Melinda can decide what is best. I don't want to hold this PR just for that

**Review by pushyamig — APPROVED** [review]

**Comment by chrisrrowland** [comment]
> @chrisrrowland if you add [some predefined text defined by Gituhub](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) like **Fixes**, Github will automatically link to the issue to PR as below
> Screen Shot 2021-06-10 at 11 11 17 AM
> 
> This is a nice Feature from Github we can leverage and the benefit of it is the Reviewer can find the issue right from the PR itself with out searching for it

It's the first line of the comment. Did I not do it correctly?

**Comment by pushyamig** [comment]
> It's the first line of the comment. Did I not do it correctly?

I added the `Fixes#77` in the description  I wasn't sure if you know aware how github links issue and PR. I did not know this until recently even though I have been working in github for past 5 years

**Comment by chrisrrowland** [comment]
> > It's the first line of the comment. Did I not do it correctly?
> 
> I added the `Fixes#77` in the description I wasn't sure if you know aware how github links issue and PR. I did not know this until recently even though I have been working in github for past 5 years

Oh Ok, I thought I did that.  Guess I forgot to on this one. Thanks for adding it.

**Comment by pushyamig** [comment]
Things are not centered now :(

Screen Shot 2021-06-10 at 12 31 34 PM

But previously it was with number

Screen Shot 2021-06-10 at 12 01 23 PM

I would say keep the centering that is more important then bullet icon or whatever people call it

**Pull request merged**
