### PR TITLE
434: Fix loading spinner within enrollment section accordion

### PR DESCRIPTION
**Pull request by jaydonkrooss**
Nests the loading backdrop inside the section ids accordion, instead of the outer component

### CODE REVIEW

**Comment by pushyamig** [comment]
I will review it today

**Comment by pushyamig** [comment]
@jaydonkrooss the issue description is about **Add Non U-M Users Multiple section** feature. But the fix seems changing the Accordion control spinner background for **Add U-M user to multiple section**. 

your fix seems to be having the grey background to just accordion. I think looks better but check with @ktowneUM if she want you keep this way or as in prod right now. Based on that create a separate issue and tag this PR with that issue

**Comment by jaydonkrooss** [comment]
> @jaydonkrooss the issue description is about **Add Non U-M Users Multiple section** option. But the fix seems changing the Accordion control spinner background for **Add U-M user to multiple section**. option
> 
> your fix seems to be having the grey background to just accordion. I think looks better but check with @ktowneUM if she want you keep this way or as in prod right now. Based on that create a separate issue and tag this PR with that issue

I see, I must have been mistaken about the original documentation of the UI bug. I've created a new issue and will try to address the original issue in a different PR

**Comment by pushyamig** [comment]
@jaydonkrooss Try to link this PR to issue#434, otherwise the Commit history will pointing the PR to wrong issue. I thing you can use `git ammend` to change the commit message. or you could create a new PR. It's up to you.

**Comment by jaydonkrooss** [comment]
@pushyamig I think I'll just create a new PR to rename the branch as well. would be simpler for me I think

**Pull request closed without merging**
